# Model arguments
model_name_or_path: Qwen/Qwen2.5-3B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
use_peft: true
load_in_4bit: false

# Training arguments
output_dir: "qwen2.5-3B-R1-factual-qa_template_1_lora_v2"
bf16: true
tf32: false  # Disabled TF32 as it's not supported in your environment
max_steps: 2000
per_device_train_batch_size: 2
gradient_accumulation_steps: 2  # Increased to reduce memory usage
gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 1.0e-6
lr_scheduler_type: cosine
warmup_ratio: 0.03

# GRPO specific parameters
beta: 0.001
max_prompt_length: 256
max_completion_length: 512  # Reduced from 1024 to save memory
num_generations: 8  # Reduced from 8 to save memory
use_vllm: False  # Disabled vllm completely
#vllm_gpu_memory_utilization: 0.4  # Removed this as we're not using vLLM

# Logging arguments
logging_strategy: steps
logging_steps: 10
evaluation_strategy: steps
eval_steps: 50
report_to:
  - tensorboard
save_strategy: steps
save_steps: 50
seed: 42

# Hugging Face Hub
push_to_hub: true
hub_strategy: every_save